### ISSUE TITLE
Replace Text Submit

### ISSUE THREAD

**Issue by elninho22** [tanmoy27112000/SimpleFormBuilder#20]
Hello Mrs,

Is it possible to change the name of the submit button to another custom one?

thanks

**Comment by tanmoy27112000** [comment]
Yes sure.

**Comment by tanmoy27112000** [comment]
package updated . now use submitButtonText to configure the text. 
If this helped you please leave a star at this repo and like the package. 
Thanks

**Comment by elninho22** [comment]
Thank you very much for the work!


Em ter., 7 de dez. de 2021 às 17:30, Tanmoy karmakar <
***@***.***> escreveu:
