### ISSUE TITLE
Style Fescription Form

### ISSUE THREAD

**Issue by elninho22** [tanmoy27112000/SimpleFormBuilder#21]
Hello, Mrs,

would it be possible to add a custom color/size to the form field descriptions?

Example:
![WhatsApp Image 2021-12-13 at 17 34 15](https://user-images.githubusercontent.com/41649681/145884685-b82308f7-ef32-45af-81a5-c92afab6bc28.jpeg)

**Comment by elninho22** [comment]
Hi,

is this possible ? It would be of great help for customization of the package.

appreciate

**Comment by tanmoy27112000** [comment]
Is it still required. Sorry I didn’t check the mail

**Comment by elninho22** [comment]
Yes ! Plis.

**Comment by tanmoy27112000** [comment]
can you explain more about the feature?

**Comment by elninho22** [comment]
Hi how are you ?

Possibility to customize the 'description' of the form, such as colors and size.
Something like TextStyle referring to data [description]. not for the description referring to the existing form.
![145884685-b82308f7-ef32-45af-81a5-c92afab6bc28](https://user-images.githubusercontent.com/41649681/148098418-c9a3ba41-cd9b-4767-acc7-b5bc8ffa57b6.jpeg)

attached image, we have the data[title] and data[description] I would like to change its size and color.

**Comment by elninho22** [comment]
Hi how are you ?

Possibility to edit the data[description], such as its color and size,

something like TextStyle for the data[description]
attached image we have the data[title] OK
and the data[description], in gray color, possibility to change the color and its size?

![145884685-b82308f7-ef32-45af-81a5-c92afab6bc28](https://user-images.githubusercontent.com/41649681/148098749-35cf58ee-9aa0-4948-91d0-79140105a4a0.jpeg)


appreciate

**Comment by tanmoy27112000** [comment]
Thank you for the clarification. yes we can add the feature

**Comment by tanmoy27112000** [comment]
now you can use decriptionTextDecoration to add textstyle use the updated package

**Comment by tanmoy27112000** [comment]
If this helped you please star the project and like the package in pub.dev

**Comment by elninho22** [comment]
very good!

it is perfect!

thank you so much!
