### ISSUE TITLE
fields on big screens (desktop / web) are very big

### ISSUE THREAD

**Issue by ahmedNY** [tanmoy27112000/SimpleFormBuilder#22]
![image](https://user-images.githubusercontent.com/14958972/196899281-5474d13d-fcb8-4f6c-a4d9-2ee7f800004a.png)

any way to scale down fields &  inputs

**Comment by tanmoy27112000** [comment]
Please provider the code snippet

**Comment by ahmedNY** [comment]
![image](https://user-images.githubusercontent.com/14958972/196915387-abe545b9-4f62-4459-9141-498b47ef1e14.png)
example included on this repo https://github.com/tanmoy27112000/SimpleFormBuilder/tree/main/example

**Comment by tanmoy27112000** [comment]
This can be easily fixed. I will change it @ahmedNY or would you like to contribute.

**Comment by tanmoy27112000** [comment]
Fixed @ahmedNY
